### ISSUE TITLE
Request: Please add rounding of attributes

### ISSUE THREAD

**Issue by monotonus** [pilotak/homeassistant-attributes#11]
Would it be possible to add rounding of attributes? Currently I use your component for reading bandwith measures out of my edgeOS router and this deliveres the following values:

MBps (Received) 0.02695465087890625
MBps (Sent) 0.0104522705078125

For displaying it in lovelace it would be enough to have 2 or 3 decimals, instead of this:

![grafik](https://user-images.githubusercontent.com/51734505/71979663-8b8e7c00-321e-11ea-9e18-359e61b14c95.png)

**Comment by skeptizzle** [comment]
+1

**Comment by aptonline** [comment]
+1

**Comment by pilotak** [comment]
Sorry for the late answer i somehow turned off notifications on issues
It would be possible but only for all entities not per one

**Comment by pilotak** [comment]
@monotonus, @skeptizzle  done, could you please test against the master branch, before releasing?
