### ISSUE TITLE
All sensors are called "Batteries"

### ISSUE THREAD

**Issue by bouwew** [pilotak/homeassistant-attributes#16]
Unfortunately, your nice components became unusable after updating to the latest master, I was using a very old version before that.
![image](https://user-images.githubusercontent.com/11290930/83899695-2b621e80-a759-11ea-8525-9a4a296bd23a.png)

Please fix this.

HA Core: 0.111.0b1
Attributes: latest master

**Comment by pilotak** [comment]
Looking at the code it looks like you are using `friendly_name` and if this is set all sensors will be named like that. Sorry for the silly question but who did it work before?

**Comment by bouwew** [comment]
Yes I am. 
I've just removed this line and now the sensor-names are back!
Thank you for pointing me in the direction of the solution.

May I suggest that you remove the friendly_name line from your example configuration? It makes no sense to have this line, why would you want all sensors being named the same?

**Comment by pilotak** [comment]
Glad it's solved. 
If you extract an attribute from only one sensor you can rename it, that is the point of having a friendly name
