### ISSUE TITLE
Enable value_template to allow intermediate calculations based on attributes

### ISSUE THREAD

**Issue by teleksterling** [pilotak/homeassistant-attributes#17]
I've got a temp sensor that is 5 degrees off, and want to subtract 5 from the value before I pass it as a sensor.

I believe that value_template is the way to accomplish this, but understand that it needs to be enabled separately for each integration - based on this section: https://www.home-assistant.io/docs/configuration/templating/#processing-incoming-data

**Comment by pilotak** [comment]
Done, please checkout master and let me know

**Comment by pilotak** [comment]
@teleksterling just add to config
```yaml
value_template: "-5"
```
