### ISSUE TITLE
Friendly name change

### ISSUE THREAD

**Issue by Dinges28** [pilotak/homeassistant-attributes#20]
Is it possible to use the friendly name of the sensor where the attribute is distilled from?
It now uses the entity name, and that is not appealing in the overall view.

**Comment by pilotak** [comment]
I believe this function is there

https://github.com/pilotak/homeassistant-attributes/blob/2a3e536d6af42a92498fbbc692a49af4fe3cff76/custom_components/attributes/sensor.py#L87

**Comment by Dinges28** [comment]
That looks good, but it shows up now as 
door_window_sensor_158d00045c7f62 43%

But the original entity has a friendly name configured:
![Screenshot 2020-07-15 at 10 37 04](https://user-images.githubusercontent.com/39988228/87523453-3c228000-c687-11ea-8b47-972d01b9c762.png)

**Comment by pilotak** [comment]
ok this looks like a bug, i will look into it.
But just to let you know, new friendly name will be "Slaapkamerkast I Battery Level" in which you case dutch and english will be mixed

**Comment by sfedotovs** [comment]
I noticed that friendly_name gets successfully copied from binary sensors, but not for sensors.
![image](https://user-images.githubusercontent.com/9420483/95012271-fd75e380-063f-11eb-8671-ba314a51e978.png)
![image](https://user-images.githubusercontent.com/9420483/95012291-226a5680-0640-11eb-92a7-a93b5f9ac5ef.png)

any plans to fix this issue?

**Comment by pilotak** [comment]
@sfedotovs there is definitely a plan to fix this, i just don't have a time as there are more important things to do. But you more than welcome to submit a PR if you faster than me

**Comment by pilotak** [comment]
It should be fixed in `device_class` branch, could you please test it?

**Comment by pilotak** [comment]
Please update to version 1.2.0.
Feel free to reopen if the problem persist
