### ISSUE TITLE
Enhancement: add device_class attribute

### ISSUE THREAD

**Issue by gee-jay-bee** [pilotak/homeassistant-attributes#25]
Some integrations use device_class to determine what to do (e.g. HomeKit uses it to expose humidity / temperature correctly). Would be great to have the ability to specify this via configuration. If the config is not specified, don't specify the device type to preserve current behaviour.

**Comment by pilotak** [comment]
fixed in `device_class` branch. Could you please test it?

**Comment by pilotak** [comment]
Added to version 1.2.0.

**Comment by gee-jay-bee** [comment]
Apologies for the late feedback but I can confirm this is working as expected ... HomeKit now correctly exposes those sensors.
