### ISSUE TITLE
Entities which start with a number are not supported

### ISSUE THREAD

**Issue by Vitani** [pilotak/homeassistant-attributes#27]
I have a sensor called `2x2_5x_3_0_players_online`, and the attributes component doesn't like it.

Using the debug logger, I found that this is the template it's trying to format -

`{% if states('sensor.2x2_5x_3_0_players_online') != 'unknown' %}{{ states.sensor.2x2_5x_3_0_players_online.attributes['players_list'] }}{% else %} unknown {% endif %}`

and this is the error I get -

> TemplateSyntaxError: expected token 'end of print statement', got 'x2_5x_3_0_players_online'

From my experimentation in the template developer tool, it's the second "2x2_5x_3_0_players_online" which causes the issue, because in python variables cannot start with a number.

*Workaround*
Rename the entity to not start with a number.

**Comment by pilotak** [comment]
please try `device_class` branch this has been fixed but to merged yet

**Comment by Vitani** [comment]
Can i do that in HACS, or will I have to manually reinstall?

**Comment by pilotak** [comment]
manually... i will release is soon

**Comment by pilotak** [comment]
i have pushed an update to HACS.
Please reopen if the problem persists
