### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'attributes'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'attributes'

### ISSUE THREAD

**Issue by haseat** [pilotak/homeassistant-attributes#28]
Logger: homeassistant.loader
Source: loader.py:802
First occurred: 6:05:34 AM (2 occurrences)
Last logged: 6:05:34 AM

No 'version' key in the manifest file for custom integration 'attributes'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'attributes'

**Comment by pilotak** [comment]
fixed in a32a831406e634120c634313c558b68e3b4e6c72 will be released soon
