### ISSUE TITLE
 ERROR custom_components.attributes.sensor - Could not attribute sensor 

### ISSUE THREAD

**Issue by Tom-ahawk** [pilotak/homeassistant-attributes#3]
The integration code creates the sensors (battery_level), but I am getting errors in the log. Anything to worry about?

![image](https://user-images.githubusercontent.com/35527507/63090768-96d5c800-bf5c-11e9-998f-1e4951453286.png)

HA log:
https://www.dropbox.com/s/qcpzsxtgrbn2frs/ha-log%20-%20attribute%20integartion%20error.txt?dl=0

**Comment by pilotak** [comment]
fixed in https://github.com/pilotak/homeassistant-attributes/pull/5
