### ISSUE TITLE
Possible wrong parameter reference

### ISSUE THREAD

**Issue by mrfind** [pilotak/homeassistant-attributes#30]
Just from reading and trying to understand the code: Shouldn't line 57 compare the state to {3} rather than {2}? Comparing it to time_format doesn't seem right. This may have happended because parameters in line 82 have a different order.

I'd try to fix it myself but I'm still new to Home Assistant programming and GitHub and I have yet to try my first pull request...

Anyway, thanks a lot for providing this component!
Martin

**Comment by pilotak** [comment]
Thanks fo finding a bug. You are right.
Anyway try to submit a PR I will review it, you can't do anything wrong.

**Comment by mrfind** [comment]
Ok, I'll look into it over the weekend. I should really learn this anyway!

**Comment by pilotak** [comment]
fixed via #31
