### ISSUE TITLE
Delete entities

### ISSUE THREAD

**Issue by alnavasa** [pilotak/homeassistant-attributes#33]
I have removed an platform: attributes from the code, and after reboot the entities still exist, how can I delete them permanently. 

(If this is already explained somewhere around the Bloggs I think should also be in the main page of this GitHub entry)

**Comment by pilotak** [comment]
Unfortunatelly there is no way to delete them automatically, you can probably do it dev-tools, or simply wait for db to drop the unused (depends on the purge interval). This intergration creates only `template sensors` the same way you would do manually meaning there is no autodelete either
