### ISSUE TITLE
Ha 2023.6.0 broke the integration

### ISSUE THREAD

**Issue by faxbio** [pilotak/homeassistant-attributes#36]
As soon as updating Ha It won t pass the reboot controls sayng that the yaml file has errors about extracting sensor attributes for every sensor i created using this custom integration

**Comment by Conundrum1911** [comment]
Same -- I had to comment/remark out all of mine to get past the errors.  Hopefully this can be patched/fixed so we can use this add-on again.

**Comment by pilotak** [comment]
Can somebody please share the error log or propose a PR

**Comment by faxbio** [comment]
Sorry, i cant. I m so fool to have rebooted even if ha said there were errors...and now i m trying to rebuild the system.i haVe no access right now...

**Comment by albatorsk** [comment]
> Can somebody please share the error log or propose a PR

Of course. Here's what home-assistant.log says:

`2023-06-07 23:00:55.797 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.attributes.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/attributes/sensor.py", line 44, in <module>
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'`

**Comment by andnp** [comment]
Looks like the upgrade to python 3.11 is what caused the break. `asyncio.coroutine` was previously deprecated and is no longer supported in python 3.11.

I believe #37 fixes the issue (works on my machine, at least!)

**Comment by pilotak** [comment]
@tefracky
> In previous HomeAssistant version, all worked fine

As exected...

please try #37

**Comment by V4n1X** [comment]
> > @tefracky
> > > In previous HomeAssistant version, all worked fine
> > 
> > 
> > As exected...
> > please try #37
> 
> I replaced my sensor.py with what was in #37 and it appears to be working again.

Can confirm it too, works with that again.

**Comment by tefracky** [comment]
With the fix, all works fine. I think you should merge it into master

**Comment by pilotak** [comment]
fixed in release v1.2.1
