### ISSUE TITLE
Friendly name not set correctly

### ISSUE THREAD

**Issue by toofewacres** [pilotak/homeassistant-attributes#4]

**Comment by toofewacres** [comment]
Friendly_name is not set correctly. New sensor uses friendly name from the original entity used.

**Comment by ameel** [comment]
I fixed the issue on my setup by modifying config/custom_components/attributes/sensor.py, and restarting home assistant as follows:

```
        if device_state is not None:
            device_friendly_name = device_state.attributes.get('friendly_name')
        else:
            device_friendly_name = None

        if device_friendly_name is None:
            device_friendly_name = device.split(".", 1)[1]
```
to
```
        if device_state is not None:
            device_friendly_name = device_state.attributes.get('friendly_name')
        else:
            device_friendly_name = device.split(".", 1)[1]
```
and
```
        if entity_state is not None:
            device_friendly_name = entity_state.attributes.get('friendly_name')
        else:
            device_friendly_name = None

        if device_friendly_name is not None:
            self._name = device_friendly_name
```
to
```
        if entity_state is not None:
            device_friendly_name = entity_state.attributes.get('friendly_name')
        else:
            self._name = device_friendly_name
```

**Comment by mcasper73** [comment]
@ameel  THANK YOU VERY MUCH for share your solution.

**Comment by nortuzar** [comment]
> I fixed the issue on my setup by modifying config/custom_components/attributes/sensor.py, and restarting home assistant as follows:
> 
> ```
>         if device_state is not None:
>             device_friendly_name = device_state.attributes.get('friendly_name')
>         else:
>             device_friendly_name = None
> 
>         if device_friendly_name is None:
>             device_friendly_name = device.split(".", 1)[1]
> ```
> 
> to
> 
> ```
>         if device_state is not None:
>             device_friendly_name = device_state.attributes.get('friendly_name')
>         else:
>             device_friendly_name = device.split(".", 1)[1]
> ```
> 
> and
> 
> ```
>         if entity_state is not None:
>             device_friendly_name = entity_state.attributes.get('friendly_name')
>         else:
>             device_friendly_name = None
> 
>         if device_friendly_name is not None:
>             self._name = device_friendly_name
> ```
> 
> to
> 
> ```
>         if entity_state is not None:
>             device_friendly_name = entity_state.attributes.get('friendly_name')
>         else:
>             self._name = device_friendly_name
> ```

Did the change and work great! Thanks

**Comment by pilotak** [comment]
merged in https://github.com/pilotak/homeassistant-attributes/pull/10
