### ISSUE TITLE
Thermostat HVAC Mode: Reporting Unknown

### ISSUE THREAD

**Issue by teek541** [pilotak/homeassistant-attributes#41]
Hello, I'm trying to extract the "hvac_action" attribute from my climate.thermostat entity.  This should report cool, heat, fan, idle, off, etc.  I want to track the current stat of my AC system.  The attribute is showing "idle" or "fan" but the created sensor is showing "unavailable".  Any idea what I might be doing wrong?

sensor:
  - platform: attributes
    friendly_name: "HVAC Mode"
    attribute: hvac_action
    entities:
      - climate.thermostat

**Comment by pilotak** [comment]
could you please share a debug

```yaml
logger:
 logs:
  custom_components.attributes: debug
```

and also make a screenshot in dev tools

**Comment by teek541** [comment]
I did do that at install, but after creating/editing the sensor in YAML I think I needed to do another restart.  Unless that was in the notification too, I may have missed that.
