### ISSUE TITLE
Request: If no attribute specified, break out all attributes from given sensors. 

### ISSUE THREAD

**Issue by fortepc** [pilotak/homeassistant-attributes#8]
I use the tautulli integration, https://www.home-assistant.io/integrations/tautulli/, and it provides a single sensor, with the playstatus of all of my server's members as attributes. I'd like to break these out at their own sensors. I currently use template sensors to do this manually, but I'd love to be able to clean up my config and have just every attribute of the tautulli sensor broken out into their own sensors.

**Comment by pilotak** [comment]
I would need to see a screenshot in `developer-tools/state` because i don't use such a component

**Comment by pilotak** [comment]
I looked into the code deeply and this is not possible. I don't have an access to see available attributes, i can only pull the specified. This components is basically an advanced template sensor where you need to know what you want to breakout.
